crc_meta_path = "../data/crc_metadata/"
doc_path = crc_meta_path+"descriptions_brat/"
agg_path = "../data/aggregated_data/"
tokc_path = "../data/token_clf_data/"
docc_path = "../data/doc_clf_data/model_input/"