tokc_path = "../data/token_clf_data/"
docc_path = "../data/doc_clf_data/"
crc_meta_path = "../data/crc_metadata/"
agg_path = "../data/aggregated_data/"
s2v_reddit_path = "../../../../../../group/project/s1545703/gender-bias/data/s2v_old"