inf_data_path = "../../data/" #"../../../../../../group/project/s1545703/gender-bias/data/"
tokc_path = inf_data_path+"token_clf_data/"
docc_path = inf_data_path+"doc_clf_data/"
crc_meta_path = inf_data_path+"crc_metadata/"
agg_path = inf_data_path+"aggregated_data/"
s2v_reddit_path = inf_data_path+"s2v_old/"
fasttext_path = "../../word_embeddings/fastText/"
glove_path = "../../word_embeddings/GloVe/"